export const CREATE_QUERY = "CREATE_QUERY";
export const PRODUCT_SERVICE = "PRODUCT_SERVICE";
export const GET_PRODUCTS_HANDLER = "GET_PRODUCTS_HANDLER";
export const GET_PRODUCT_OPTIONS_HANDLER = "GET_PRODUCT_OPTIONS_HANDLER";
export const CREATE_PRODUCT_HANDLER = "CREATE_PRODUCT_HANDLER";
